// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeYkrqEzgTuFkkJlDSYnLXn5KxerUMbvw',
    appId: '1:896737755901:web:b51682a50b9b0c549d7494',
    messagingSenderId: '896737755901',
    projectId: 'craft-my-plate-96220',
    authDomain: 'craft-my-plate-96220.firebaseapp.com',
    storageBucket: 'craft-my-plate-96220.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8dedgLnxOLQEE3Nes9w2FSZevni2ATc4',
    appId: '1:896737755901:android:12bd42f1357a2b1a9d7494',
    messagingSenderId: '896737755901',
    projectId: 'craft-my-plate-96220',
    storageBucket: 'craft-my-plate-96220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg9S4F8KV_ziN1A0T8uKRohnhTrqEx5fs',
    appId: '1:896737755901:ios:4c1f40e7cec767d09d7494',
    messagingSenderId: '896737755901',
    projectId: 'craft-my-plate-96220',
    storageBucket: 'craft-my-plate-96220.appspot.com',
    iosBundleId: 'com.example.craftMyPlate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg9S4F8KV_ziN1A0T8uKRohnhTrqEx5fs',
    appId: '1:896737755901:ios:4c1f40e7cec767d09d7494',
    messagingSenderId: '896737755901',
    projectId: 'craft-my-plate-96220',
    storageBucket: 'craft-my-plate-96220.appspot.com',
    iosBundleId: 'com.example.craftMyPlate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeYkrqEzgTuFkkJlDSYnLXn5KxerUMbvw',
    appId: '1:896737755901:web:8841bcc5f94c3a699d7494',
    messagingSenderId: '896737755901',
    projectId: 'craft-my-plate-96220',
    authDomain: 'craft-my-plate-96220.firebaseapp.com',
    storageBucket: 'craft-my-plate-96220.appspot.com',
  );
}
